export const projects = [
    { 
        title: "Reviewing the Collaboration Side of Google Docs",
        url: "googledocsusabilityreview",
        banner: require("./images/docs.jpg"),
        genre: "Usability Review",
        client:"Postman",
        brief: "A UX centered analysis of the collaborative side of Google Docs based on Nielsen's Heuristics",
        medium: "https://medium.com/@utkarshgill07/collaboration-over-google-docs-a-not-so-good-experience-5c3caca86cdc?sk=55b18fad41c7297f348087911c4d6c84",
        behance: "https://www.behance.net/gallery/99052941/Collaborative-Side-of-Google-Docs-A-Usability-Review",
    },
    { 
        title: "Can a Simple Chrome Extension save the Recruiters Loads of Headache?",
        url: "hiringconsole",
        banner: require("./images/hiring-console.jpg"),
        genre: "Product Design",
        client:"Procol",
        brief: "A simple and feasible chrome extension for Gmail to help the recruiters manage candidates' applications and track the recruitment process",
        behance: "https://www.behance.net/gallery/97758399/Hiring-Console",
    },
    { 
        title: "Designing a Social Credit System",
        url: "nutanixdesigncompetition2020",
        banner: require("./images/cimba.jpg"),
        genre: "Product & System Design",
        client:"Nutanix Design Competition 2020",
        brief: "The goal was to imagine the working of a social rating system & design an interface that helps the Mayor to monitor the city’s state, identify issues & suggest solutions and rate the citizens based on that system",
        duration: "10 days (March '19)",
        roles: "System Analysis\nPlanning & Ideation\nIntegration\nWorkflows\nUser Research\nJourney Mapping\nWireframes\nScenarios\n",
        medium: "https://medium.com/usabilitygeek/240-hours-of-ux-nutanix-design-competition-f3a98123ccdb",
    },
    {    
        title: "Redesigning a Marketplace tool for the Employees",
        url: "wheelseyewinterinternship",
        banner: require("./images/odin.jpg"),
        genre: "product design",
        client:"Wheelseye",
        brief: "As the number of employees in Wheelseye increases, how might we redesign Odin to deliver efficiency and a better experience for the employees?",
        duration: "2 months (Dec'19 - Jan'20)",
        roles: "User Research\nJourney Mapping\nInformation Architecture\nWorklows\nWireframing\n",
        medium: "https://medium.com/design-studio-iit-roorkee/designing-for-the-employees-winter-2019-internship-at-wheelseye-8b9c15705670",
    },
    { 
        title: "A Hands-Free Cooking Assistant for Indian Households",
        url: "handsfreecookingassitant",
        banner: require("./images/kookerr.jpg"),
        genre: "UI/UX design",
        client:"Design Studio IITR",
        brief: "A voice-activated cooking assistant cum recipe app, designed focusing on indian households & their requirements",
        duration: "15 days (March '19)",
        roles: "User Research\nCompetitive Analysis\nUser Flows\nInformation Structuring\nWireframing\nPrototyping\n",
        medium: "https://medium.com/design-studio-iit-roorkee/a-hands-free-cooking-assistant-daa2fec255d",
        behance: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX",
    },
]