export const projects = [ 
    {    
        title: "ODIN - The Marketplace Cerebrum",
        thumbnail: require("./images/test.jpg"),
        banner: require("./images/test-ls.jpg"),
        genre: "product design",
        client:"Wheelseye Technologies",
        brief: "ODIN is a supply-demand management portal for a logistics based startup - Wheelseye. It is an internal product mainly used by the employees.",
        duration: "2 months (Dec'19 - Jan'20)",
        roles: "User Research\nUser Interview\nJourney Mapping",
        medium: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX",
        behance: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX"
    },
    { 
        title: "Kookerr - A hands-free cooking assistant",
        thumbnail: require("./images/test.jpg"),
        banner: require("./images/test-ls.jpg"),
        genre: "UI/UX design",
        client:"Design Studio IITR",
        brief: "ODIN is a supply-demand management portal for a logistics based startup - Wheelseye. It is an internal product mainly used by the employees.",
        duration: "2 months (Dec'19 - Jan'20)",
        roles: "User Research\nUser Interview\nJourney Mapping",
        medium: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX",
        behance: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX",
    },
    { 
        title: "A Ferocious Beauty",
        thumbnail: require("./images/test.jpg"),
        banner: require("./images/test-ls.jpg"),
        genre: "graphic design",
        client:"Kshitij - The Literary Magazine",
        brief: "ODIN is a supply-demand management portal for a logistics based startup - Wheelseye. It is an internal product mainly used by the employees.",
        duration: "2 months (Dec'19 - Jan'20)",
        roles: "User Research\nUser Interview\nJourney Mapping",
        medium: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX",
        behance: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX"
    },
    {    
        title: "ODIN - The Marketplace Cerebrum",
        thumbnail: require("./images/test.jpg"),
        banner: require("./images/test-ls.jpg"),
        genre: "product design",
        client:"Wheelseye Technologies",
        brief: "ODIN is a supply-demand management portal for a logistics based startup - Wheelseye. It is an internal product mainly used by the employees.",
        duration: "2 months (Dec'19 - Jan'20)",
        roles: "User Research\nUser Interview\nJourney Mapping",
        medium: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX",
        behance: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX"
    },
    { 
        title: "Kookerr - A hands-free cooking assistant",
        thumbnail: require("./images/test.jpg"),
        banner: require("./images/test-ls.jpg"),
        genre: "UI/UX design",
        client:"Design Studio IITR",
        brief: "ODIN is a supply-demand management portal for a logistics based startup - Wheelseye. It is an internal product mainly used by the employees.",
        duration: "2 months (Dec'19 - Jan'20)",
        roles: "User Research\nUser Interview\nJourney Mapping",
        medium: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX",
        behance: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX"
    },
    { 
        title: "A Ferocious Beauty",
        thumbnail: require("./images/test.jpg"),
        banner: require("./images/test-ls.jpg"),
        genre: "graphic design",
        client:"Kshitij - The Literary Magazine",
        brief: "ODIN is a supply-demand management portal for a logistics based startup - Wheelseye. It is an internal product mainly used by the employees.",
        duration: "2 months (Dec'19 - Jan'20)",
        roles: "User Research\nUser Interview\nJourney Mapping",
        medium: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX",
        behance: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX"
    },
    {    
        title: "ODIN - The Marketplace Cerebrum",
        thumbnail: require("./images/test.jpg"),
        banner: require("./images/test-ls.jpg"),
        genre: "product design",
        client:"Wheelseye Technologies",
        brief: "ODIN is a supply-demand management portal for a logistics based startup - Wheelseye. It is an internal product mainly used by the employees.",
        duration: "2 months (Dec'19 - Jan'20)",
        roles: "User Research\nUser Interview\nJourney Mapping",
        medium: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX",
        behance: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX"
    },
    { 
        title: "Kookerr - A hands-free cooking assistant",
        thumbnail: require("./images/test.jpg"),
        banner: require("./images/test-ls.jpg"),
        genre: "UI/UX design",
        client:"Design Studio IITR",
        brief: "ODIN is a supply-demand management portal for a logistics based startup - Wheelseye. It is an internal product mainly used by the employees.",
        duration: "2 months (Dec'19 - Jan'20)",
        roles: "User Research\nUser Interview\nJourney Mapping",
        medium: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX",
        behance: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX"
    },
    { 
        title: "A Ferocious Beauty",
        thumbnail: require("./images/test.jpg"),
        banner: require("./images/test-ls.jpg"),
        genre: "graphic design",
        client:"Kshitij - The Literary Magazine",
        brief: "ODIN is a supply-demand management portal for a logistics based startup - Wheelseye. It is an internal product mainly used by the employees.",
        duration: "2 months (Dec'19 - Jan'20)",
        roles: "User Research\nUser Interview\nJourney Mapping",
        medium: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX",
        behance: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX"
    },
    {    
        title: "ODIN - The Marketplace Cerebrum",
        thumbnail: require("./images/test.jpg"),
        banner: require("./images/test-ls.jpg"),
        genre: "product design",
        client:"Wheelseye Technologies",
        brief: "ODIN is a supply-demand management portal for a logistics based startup - Wheelseye. It is an internal product mainly used by the employees.",
        duration: "2 months (Dec'19 - Jan'20)",
        roles: "User Research\nUser Interview\nJourney Mapping",
        medium: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX",
        behance: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX"
    },
    { 
        title: "Kookerr - A hands-free cooking assistant",
        thumbnail: require("./images/test.jpg"),
        banner: require("./images/test-ls.jpg"),
        genre: "UI/UX design",
        client:"Design Studio IITR",
        brief: "ODIN is a supply-demand management portal for a logistics based startup - Wheelseye. It is an internal product mainly used by the employees.",
        duration: "2 months (Dec'19 - Jan'20)",
        roles: "User Research\nUser Interview\nJourney Mapping",
        medium: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX",
        behance: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX"
    },
    { 
        title: "A Ferocious Beauty",
        thumbnail: require("./images/test.jpg"),
        banner: require("./images/test-ls.jpg"),
        genre: "graphic design",
        client:"Kshitij - The Literary Magazine",
        brief: "ODIN is a supply-demand management portal for a logistics based startup - Wheelseye. It is an internal product mainly used by the employees.",
        duration: "2 months (Dec'19 - Jan'20)",
        roles: "User Research\nUser Interview\nJourney Mapping",
        medium: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX",
        behance: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX"
    },
]